### ISSUE TITLE
emby-updater 0.7.2 no longer updating emby

### ISSUE THREAD

**Issue by frankyw** [shokinn/emby-updater#1]
Hi Philip,

Firstly, thanks for the great piece of software, it has been working perfectly for a while now.

However, I am using the emby-updater 0.7.2 binary, and as of Emby 4.1.0.8 beta it no longer seems to work. Emby dashboard shows 4.1.0.10 beta as available, yet emby-updater can't see an update.

Any help greatly appreciated!

**Comment by shokinn** [comment]
Hey @frankyw sorry for my late response.
I'll probably take a look on sunday on this.

Could you send me the following infos, please?
OS:
Distribution version (binary/pip): binary
emby-updater version:
Which emby-updater flags do you use? (e.g. `--beta`):
Emby version:

**Comment by frankyw** [comment]
Hi @shokinn this seems to be working again now without further intervention, not sure what happened, but it looked like a temporary issue. Thanks!
