### ISSUE TITLE
Can’t use --help as non-root user

### ISSUE THREAD

**Issue by luziferius** [shokinn/emby-updater#2]
As far as I can see, the first thing `main()` does is to check if it runs as root, even before the argument parser is built:

https://github.com/shokinn/emby-updater/blob/9c3aaa72f55a5a3624e8c6695784110d09f93a22/embyupdater/__init__.py#L177-L184

I think this is a bit restrictive. If you move the check below https://github.com/shokinn/emby-updater/blob/9c3aaa72f55a5a3624e8c6695784110d09f93a22/embyupdater/__init__.py#L200
both `--help` and `--version` can be used as non-root, while the system-altering functions are still protected.

**Comment by ulrick65** [comment]
This is not a bad idea...not a major issue mind you, but might be cleaner for some folks.  The other thing I thought of was if you do run it as non-root, you could say so (like it does) but then also display the help info as if --help was specified.  Just an idea.

Great tool here, it works perfectly for me.

**Comment by shokinn** [comment]
Fixed in d59bdd07b01c38411272c9999f0f47cd3962f985

Sorry @luziferius, I've totally overlooked your issue -.-
