### ISSUE TITLE
Request - Show Version Number When Update Not Required

### ISSUE THREAD

**Issue by ulrick65** [shokinn/emby-updater#3]
It would be nice (not required, but nice) if when I run it it would display my version and the current version no matter what...even if they are the same.  Not a lot of value add, but would at least tell me that it checked and did not have some other problem...it actually found both, compared them...and here they are...and "No update available."

Thanks for this tool...it is excellent and works quite well...not only that if fills a real need for those of us running on Linux.

**Comment by shokinn** [comment]
Hi @ulrick65,
there will be thrown an error when the updater can't find any releases.

https://github.com/shokinn/emby-updater/blob/9c3aaa72f55a5a3624e8c6695784110d09f93a22/embyupdater/__init__.py#L135-L136

But I'll also implement your request to show both version numbers, when there is no new release.

**Comment by shokinn** [comment]
Feature added in ae04e6a2b438b7bc612bbdb6379ec2b5b5ee3fab

**Comment by ulrick65** [comment]
Well done!  Works like a charm!
